### ISSUE TITLE
two typos

### ISSUE THREAD

**Issue by nikoss** [LiMinggang/madedit-mod#82]
In the pot file there seem to be two mistakes:
Langurage
Thesauri

Maybe it should be...:
Language
Thesaurus

![madedit-mod_-_typo_001](https://cloud.githubusercontent.com/assets/4921343/11169322/d70fb05c-8bbc-11e5-9ca0-b78c4add5226.jpg)

**Comment by LiMinggang** [comment]
Thanks for reporting!

**Comment by LiMinggang** [comment]
The "Langurage" is a Typo. However, "Thesauri" is not. I'm not a native English speaker(I borrow it from Code::Blocks), so, I googled it. Below is from wiki.
https://en.wikipedia.org/wiki/Controlled_vocabulary

"There are two main kinds of controlled vocabulary tools used in libraries: subject headings and thesauri. While the differences between the two are diminishing, there are still some minor differences.

Historically subject headings were designed to describe books in library catalogs by catalogers while thesauri were used by indexers to apply index terms to documents and articles. Subject headings tend to be broader in scope describing whole books, while thesauri tend to be more specialized covering very specific disciplines. Also because of the card catalog system, subject headings tend to have terms that are in indirect order (though with the rise of automated systems this is being removed), while thesaurus terms are always in direct order. Subject headings also tend to use more pre-coordination of terms such that the designer of the controlled vocabulary will combine various concepts together to form one authorized subject heading. (e.g., children and terrorism) while thesauri tend to use singular direct terms. Lastly thesauri list not only equivalent terms but also narrower, broader terms and related terms among various authorized and non-authorized terms, while historically most subject headings did not."

**Comment by nikoss** [comment]
One more possible typo:

> Catched a exception of 'regex_error'.\n
> Maybe the regular expression is invalid.


Maybe it is...
> Cached an exception

or...
> Caught an exception

**Comment by LiMinggang** [comment]
Caught an exception, will fix it.

**Comment by nikoss** [comment]
Hi, again, a few more that might be typos, followed by possible corrections:

List all files had been opened before
List all files that had been opened before

Copy full file name without extention
Copy full file name without extension

&Dselect All
&Deselect All

Indent after parens
maybe...
Indent after parents

**Comment by LiMinggang** [comment]
Fixed all excepts the last which is from Astyle "parens" is for parenthesis in program lanuage, ie, ( ),

**Comment by LiMinggang** [comment]
I also put Greek Dictionary in the Directories directory in case you need it. They are from OpenOffice.

**Comment by nikoss** [comment]
Ok, another possible typo:
Insert pair instead of replace selection

Maybe better...
Insert pair instead of replacing selection

**Comment by nikoss** [comment]
And one more...

`Previw: `
`Preview: `

In both cases, having an extra space character, at the end.
